const mongoose = require('mongoose');
const Question = require('./models/Question');
require('dotenv').config();

mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });

const questions = [
  { question: "Pineapple on pizza?", optionA: "Yes, love it!", optionB: "No way!" },
  { question: "Cats or dogs?", optionA: "Cats", optionB: "Dogs" },
  { question: "Early bird or night owl?", optionA: "Early bird", optionB: "Night owl" },
  { question: "Coffee or tea?", optionA: "Coffee", optionB: "Tea" },
  { question: "Beach or mountains?", optionA: "Beach", optionB: "Mountains" },
  { question: "Read a book or watch a movie?", optionA: "Read a book", optionB: "Watch a movie" },
  { question: "Summer or winter?", optionA: "Summer", optionB: "Winter" },
  { question: "Introvert or extrovert?", optionA: "Introvert", optionB: "Extrovert" },
  { question: "Travel by plane or train?", optionA: "Plane", optionB: "Train" },
  { question: "Sweet or savory?", optionA: "Sweet", optionB: "Savory" },
  { question: "Hostel life or home life?", optionA: "Hostel", optionB: "Home" },
  { question: "Attend 8 AM class or skip?", optionA: "Attend", optionB: "Skip" },
  { question: "Canteen food or Swiggy?", optionA: "Canteen", optionB: "Swiggy" },
  { question: "ACAD block or TT block?", optionA: "ACAD", optionB: "TT" },
  { question: "VIT Fest or Tech Event?", optionA: "Fest", optionB: "Tech Event" },
  { question: "Are you a VITian or Not?", optionA: "Yes, I am!", optionB: "No, but curious!" },
  { question: "Netflix or YouTube binge?", optionA: "Netflix", optionB: "YouTube" },
  { question: "Cricket or Football?", optionA: "Cricket", optionB: "Football" },
  { question: "Group study or solo grind?", optionA: "Group", optionB: "Solo" },
  { question: "Front row or back bench?", optionA: "Front", optionB: "Back" },
  { question: "Have you bunked classes?", optionA: "Too many!", optionB: "Never!" },
  { question: "Roommate or single room?", optionA: "Roommate", optionB: "Single room" },
  { question: "Assignments last minute?", optionA: "Always", optionB: "Done early" },
  { question: "Mess food: Good or nah?", optionA: "It's okay", optionB: "Disaster" },
  { question: "Codechef or Leetcode?", optionA: "Codechef", optionB: "Leetcode" },
  { question: "Dance club or coding club?", optionA: "Dance", optionB: "Coding" },
  { question: "Do you pull all-nighters?", optionA: "Yes", optionB: "Never" },
  { question: "Thalapakatti or VIT mess?", optionA: "Thalapakatti", optionB: "VIT mess" },
  { question: "TNEA or VITEEE?", optionA: "TNEA", optionB: "VITEEE" },
  { question: "VR Mall weekend plan?", optionA: "Yes!", optionB: "Too far!" },
  { question: "Is SRM better than VIT?", optionA: "No way!", optionB: "Hmm maybe" },
  { question: "Did you choose VIT or parents did?", optionA: "Me", optionB: "Parents" },
  { question: "100% attendance goal?", optionA: "Yes", optionB: "LOL no" },
  { question: "Textbooks or YouTube tutors?", optionA: "Textbooks", optionB: "YouTube" },
  { question: "Shirt tucked in or out?", optionA: "Tucked in", optionB: "Out always" },
  { question: "Favorite VIT block?", optionA: "SJT", optionB: "TT" },
  { question: "Hostel wifi or mobile data?", optionA: "Wifi", optionB: "Mobile" },
  { question: "CLUBS or STUDIES?", optionA: "CLUBS", optionB: "STUDIES" },
  { question: "VIT food stalls or city cafes?", optionA: "Food stalls", optionB: "City cafes" },
  { question: "Do you like group projects?", optionA: "Yes", optionB: "Hate them" },
  { question: "Snapchat or Instagram?", optionA: "Snapchat", optionB: "Instagram" },
  { question: "Linux or Windows?", optionA: "Linux", optionB: "Windows" },
  { question: "VIT tech events: Fun or boring?", optionA: "Fun!", optionB: "Boring" },
  { question: "Would you date a batchmate?", optionA: "Yes", optionB: "No" },
  { question: "Part-time job or chill?", optionA: "Job", optionB: "Chill" },
  { question: "CGPA or startup dream?", optionA: "CGPA", optionB: "Startup" },
  { question: "Laptop stickers: Cool or cringe?", optionA: "Cool", optionB: "Cringe" },
  { question: "Would you marry a VITian?", optionA: "Yes", optionB: "Let’s see" },
  { question: "Did you ever fake sick to skip class?", optionA: "Many times", optionB: "Never" },
  { question: "Python or Java?", optionA: "Python", optionB: "Java" },
  { question: "LinkedIn addict or Instagram model?", optionA: "LinkedIn", optionB: "Instagram" },
  { question: "Rewatch F.R.I.E.N.D.S or try new?", optionA: "Rewatch", optionB: "Try new" },
  { question: "Gym or Sleep?", optionA: "Gym", optionB: "Sleep" },
  { question: "Plan assignments or wing it?", optionA: "Plan", optionB: "Wing it" },
  { question: "Night canteen or 7 PM dinner?", optionA: "Night canteen", optionB: "7 PM dinner" },
  { question: "Chai breaks every day?", optionA: "Yes", optionB: "Nope" },
  { question: "VIT OP hostel or main hostel?", optionA: "OP", optionB: "Main" },
  { question: "Hackathons or fests?", optionA: "Hackathons", optionB: "Fests" },
  { question: "F.R.I.E.N.D.S or Big Bang Theory?", optionA: "F.R.I.E.N.D.S", optionB: "BBT" },
  { question: "Crush in class?", optionA: "Yes", optionB: "No" },
  { question: "Android or iOS?", optionA: "Android", optionB: "iOS" },
  { question: "Spoken to a VIT senior?", optionA: "Yeah", optionB: "Not yet" },
  { question: "Should attendance be optional?", optionA: "YES!", optionB: "No, it’s okay" },
  { question: "Are clubs actually useful?", optionA: "Very", optionB: "Nope" },
  { question: "Do you prefer hybrid classes?", optionA: "Yes", optionB: "No" },
  { question: "Online exams or offline?", optionA: "Online", optionB: "Offline" },
  { question: "Daily bathing in hostel?", optionA: "Everyday", optionB: "Sometimes" },
  { question: "Game night or movie night?", optionA: "Game night", optionB: "Movie night" },
  { question: "Do you know VIT dress code?", optionA: "Yes", optionB: "Wait…what?" },
  { question: "Internship in Chennai or abroad?", optionA: "Chennai", optionB: "Abroad" },
  { question: "Does GPA matter?", optionA: "A lot", optionB: "Not really" },
  { question: "VIT VTOP UI: Decent or disaster?", optionA: "Decent", optionB: "Disaster" },
  { question: "Online crush in class group?", optionA: "Guilty", optionB: "Nope" },
  { question: "Would you work on campus?", optionA: "Yes", optionB: "No" },
  { question: "Do you remember your VITEE rank?", optionA: "Yes", optionB: "I buried it" },
  { question: "First crush was from VIT?", optionA: "Yes", optionB: "No" },
  { question: "Sneaked out of hostel?", optionA: "Yes", optionB: "Never" },
  { question: "Ever argued with faculty?", optionA: "Yes", optionB: "No" },
  { question: "VIT - strict or chill?", optionA: "Strict", optionB: "Chill" },
  { question: "Do you miss school days?", optionA: "Yes", optionB: "Not really" },
  { question: "Do you think you’ll pass all subjects?", optionA: "Of course", optionB: "Let’s hope" },
  { question: "Do you believe in love at VIT?", optionA: "Yes", optionB: "LMAO no" }
];

Question.insertMany(questions)
  .then(() => {
    console.log('Questions seeded!');
    mongoose.disconnect();
  })
  .catch(err => {
    console.error(err);
    mongoose.disconnect();
  }); 
