const mongoose = require('mongoose');
const Question = require('./models/Question');
require('dotenv').config();

mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });

const questions = [
  { question: "Pineapple on pizza?", optionA: "Yes, love it!", optionB: "No way!" },
  { question: "Cats or dogs?", optionA: "Cats", optionB: "Dogs" },
  { question: "Early bird or night owl?", optionA: "Early bird", optionB: "Night owl" },
  { question: "Coffee or tea?", optionA: "Coffee", optionB: "Tea" },
  { question: "Beach or mountains?", optionA: "Beach", optionB: "Mountains" },
  { question: "Read a book or watch a movie?", optionA: "Read a book", optionB: "Watch a movie" },
  { question: "Summer or winter?", optionA: "Summer", optionB: "Winter" },
  { question: "Introvert or extrovert?", optionA: "Introvert", optionB: "Extrovert" },
  { question: "Travel by plane or train?", optionA: "Plane", optionB: "Train" },
  { question: "Sweet or savory?", optionA: "Sweet", optionB: "Savory" },
  { question: "Hostel life or home life?", optionA: "Hostel", optionB: "Home" },
  { question: "Attend 8 AM class or skip?", optionA: "Attend", optionB: "Skip" },
  { question: "Canteen food or Swiggy?", optionA: "Canteen", optionB: "Swiggy" },
  { question: "ACAD block or TT block?", optionA: "ACAD", optionB: "TT" },
  { question: "VIT Fest or Tech Event?", optionA: "Fest", optionB: "Tech Event" },
  { question: "Are you a VITian or Not?", optionA: "Yes, I am!", optionB: "No, but curious!" },
  { question: "Netflix or YouTube binge?", optionA: "Netflix", optionB: "YouTube" },
  { question: "Cricket or Football?", optionA: "Cricket", optionB: "Football" },
  { question: "Group study or solo grind?", optionA: "Group", optionB: "Solo" },
  { question: "Front row or back bench?", optionA: "Front", optionB: "Back" },
  { question: "Early bird or night owl?", optionA: "Early bird", optionB: "Night owl" },
  { question: "Canteen chai or CCD coffee?", optionA: "Chai", optionB: "Coffee" },
  { question: "Exam prep: Notes or YouTube?", optionA: "Notes", optionB: "YouTube" },
  { question: "Mac or Windows?", optionA: "Mac", optionB: "Windows" },
  { question: "Biryani or Pizza?", optionA: "Biryani", optionB: "Pizza" },
  { question: "Introvert or extrovert?", optionA: "Introvert", optionB: "Extrovert" },
  { question: "Texting or calling?", optionA: "Texting", optionB: "Calling" },
  { question: "Hostel life or home comfort?", optionA: "Hostel", optionB: "Home" },
  { question: "Android or iOS?", optionA: "Android", optionB: "iOS" },
  { question: "Netflix night or party night?", optionA: "Netflix", optionB: "Party" },
  { question: "Tinder or Instagram?", optionA: "Tinder", optionB: "Instagram" },
  { question: "Procrastinate or plan?", optionA: "Procrastinate", optionB: "Plan" },
  { question: "Rainy days or sunny vibes?", optionA: "Rainy", optionB: "Sunny" },
  { question: "Travel solo or with squad?", optionA: "Solo", optionB: "Squad" },
  { question: "Coding at 2am or 2pm?", optionA: "2am", optionB: "2pm" },
  { question: "Jeans or joggers?", optionA: "Jeans", optionB: "Joggers" },
  { question: "Laptop or tablet for class?", optionA: "Laptop", optionB: "Tablet" },
  { question: "Startup or MNC?", optionA: "Startup", optionB: "MNC" },
  { question: "Hackathon or chillathon?", optionA: "Hackathon", optionB: "Chillathon" },
  { question: "Train or flight travel?", optionA: "Train", optionB: "Flight" },
  { question: "Comedy movies or thrillers?", optionA: "Comedy", optionB: "Thriller" },
  { question: "Spotify or Apple Music?", optionA: "Spotify", optionB: "Apple Music" },
  { question: "Sneakers or slippers?", optionA: "Sneakers", optionB: "Slippers" },
  { question: "Public speaking: Love it or hate it?", optionA: "Love it", optionB: "Hate it" },
  { question: "Gym or yoga?", optionA: "Gym", optionB: "Yoga" },
  { question: "First bench or back bench?", optionA: "First", optionB: "Back" },
  { question: "Eat out or Swiggy in?", optionA: "Eat out", optionB: "Swiggy" },
  { question: "Python or Java?", optionA: "Python", optionB: "Java" },
  { question: "Electric bike or cycle?", optionA: "E-bike", optionB: "Cycle" },
  { question: "Google Meet or Zoom?", optionA: "Meet", optionB: "Zoom" },
  { question: "Campus fest or tech fest?", optionA: "Campus", optionB: "Tech" },
  { question: "Hostel crush or class crush?", optionA: "Hostel", optionB: "Class" },
  { question: "Wake up with alarm or naturally?", optionA: "Alarm", optionB: "Naturally" },
  { question: "Read books or watch reels?", optionA: "Books", optionB: "Reels" },
  { question: "Summer break or winter break?", optionA: "Summer", optionB: "Winter" },
  { question: "Slides or shoes?", optionA: "Slides", optionB: "Shoes" },
  { question: "Eat to live or live to eat?", optionA: "Eat to live", optionB: "Live to eat" },
  { question: "Online or in-person classes?", optionA: "Online", optionB: "In-person" },
  { question: "Unlimited data or unlimited battery?", optionA: "Data", optionB: "Battery" },
  { question: "Hostel parties or night-outs?", optionA: "Hostel", optionB: "Night-out" },
  { question: "F.R.I.E.N.D.S or The Office?", optionA: "F.R.I.E.N.D.S", optionB: "The Office" },
  { question: "Exam toppers or event organizers?", optionA: "Toppers", optionB: "Organizers" },
  { question: "Hoodie or jacket?", optionA: "Hoodie", optionB: "Jacket" },
  { question: "Crush on prof or TA?", optionA: "Prof", optionB: "TA" },
  { question: "GPay or PhonePe?", optionA: "GPay", optionB: "PhonePe" },
  { question: "Samosa or sandwich?", optionA: "Samosa", optionB: "Sandwich" },
  { question: "Coding solo or with team?", optionA: "Solo", optionB: "Team" },
  { question: "Tea break or smoke break?", optionA: "Tea", optionB: "Smoke" },
  { question: "Sneak food in class?", optionA: "Yes", optionB: "Never" },
  { question: "DJ night or movie night?", optionA: "DJ", optionB: "Movie" },
  { question: "Bunk and regret or attend and yawn?", optionA: "Bunk", optionB: "Attend" },
  { question: "Hot maggi or cold pizza?", optionA: "Maggi", optionB: "Pizza" },
  { question: "Dine with SRK or Elon Musk?", optionA: "SRK", optionB: "Elon" },
  { question: "Canteen dosa or rolls?", optionA: "Dosa", optionB: "Rolls" },
  { question: "RedBull or Coffee for all-nighter?", optionA: "RedBull", optionB: "Coffee" },
  { question: "Train travel with friends or flight alone?", optionA: "Train with friends", optionB: "Flight solo" },
  { question: "Intern in Delhi or Bangalore?", optionA: "Delhi", optionB: "Bangalore" },
  { question: "Fan of Elon or Zuckerberg?", optionA: "Elon", optionB: "Zuck" },
  { question: "Coding in C or Python?", optionA: "C", optionB: "Python" },
  { question: "Exam pass or mass bunk?", optionA: "Pass", optionB: "Mass bunk" },
  { question: "Late night street food or early breakfast?", optionA: "Street food", optionB: "Breakfast" },
  { question: "Attend 8am lecture or sleep in?", optionA: "Attend", optionB: "Sleep" },
  { question: "Figma or Canva?", optionA: "Figma", optionB: "Canva" },
  { question: "Study music: Lo-fi or silence?", optionA: "Lo-fi", optionB: "Silence" },
  { question: "One best friend or large group?", optionA: "One", optionB: "Group" },
  { question: "Morning classes or evening labs?", optionA: "Morning", optionB: "Evening" },
  { question: "Group chat mute or active?", optionA: "Mute", optionB: "Active" },
  { question: "Laptop stickers or clean lid?", optionA: "Stickers", optionB: "Clean" },
  { question: "Call faculty ‘sir’ or ‘bro’?", optionA: "Sir", optionB: "Bro 😅" },
  { question: "Library desk or bean bag study?", optionA: "Desk", optionB: "Bean bag" },
  { question: "Google Scholar or ChatGPT?", optionA: "Scholar", optionB: "ChatGPT 😎" },
  { question: "Midnight coding or midnight snacks?", optionA: "Coding", optionB: "Snacks" },
  { question: "New jeans or new kicks?", optionA: "Jeans", optionB: "Kicks" },
  { question: "Lecture notes or class recordings?", optionA: "Notes", optionB: "Recordings" },
  { question: "Friend zone or ghosted?", optionA: "Friend zone", optionB: "Ghosted" },
  { question: "MacBook Air or Pro?", optionA: "Air", optionB: "Pro" },
  { question: "LinkedIn stalk or Insta stalk?", optionA: "LinkedIn", optionB: "Instagram" },
  { question: "Cultural fests or tech fests?", optionA: "Cultural", optionB: "Tech" },
  { question: "Final year project: solo or team?", optionA: "Solo", optionB: "Team" },
  { question: "Coding in nightwear or formals?", optionA: "Nightwear", optionB: "Formals" },
  { question: "Slide presenter or silent participant?", optionA: "Presenter", optionB: "Silent" },
  { question: "Netflix: Skip intro or not?", optionA: "Skip", optionB: "Watch full" },
  { question: "VIT boy hostel or girl hostel better?", optionA: "Boy hostel", optionB: "Girl hostel" },
  { question: "Viva or written test?", optionA: "Viva", optionB: "Written" },
  { question: "One crush or many flings?", optionA: "One", optionB: "Many" },
  { question: "One-sided love or no love?", optionA: "One-sided", optionB: "No love" },
  { question: "Stay in India or go abroad?", optionA: "India", optionB: "Abroad" },
  { question: "Be a coder or a creator?", optionA: "Coder", optionB: "Creator" },
  { question: "Hack someone’s WiFi or cry in hostel?", optionA: "Hack 😈", optionB: "Cry 😭" },
  { question: "Have you bunked classes?", optionA: "Too many!", optionB: "Never!" },
  { question: "Roommate or single room?", optionA: "Roommate", optionB: "Single room" },
  { question: "Assignments last minute?", optionA: "Always", optionB: "Done early" },
  { question: "Mess food: Good or nah?", optionA: "It's okay", optionB: "Disaster" },
  { question: "Codechef or Leetcode?", optionA: "Codechef", optionB: "Leetcode" },
  { question: "Dance club or coding club?", optionA: "Dance", optionB: "Coding" },
  { question: "Do you pull all-nighters?", optionA: "Yes", optionB: "Never" },
  { question: "Thalapakatti or VIT mess?", optionA: "Thalapakatti", optionB: "VIT mess" },
  { question: "TNEA or VITEEE?", optionA: "TNEA", optionB: "VITEEE" },
  { question: "VR Mall weekend plan?", optionA: "Yes!", optionB: "Too far!" },
  { question: "Is SRM better than VIT?", optionA: "No way!", optionB: "Hmm maybe" },
  { question: "Did you choose VIT or parents did?", optionA: "Me", optionB: "Parents" },
  { question: "100% attendance goal?", optionA: "Yes", optionB: "LOL no" },
  { question: "Textbooks or YouTube tutors?", optionA: "Textbooks", optionB: "YouTube" },
  { question: "Shirt tucked in or out?", optionA: "Tucked in", optionB: "Out always" },
  { question: "Favorite VIT block?", optionA: "SJT", optionB: "TT" },
  { question: "Hostel wifi or mobile data?", optionA: "Wifi", optionB: "Mobile" },
  { question: "CLUBS or STUDIES?", optionA: "CLUBS", optionB: "STUDIES" },
  { question: "VIT food stalls or city cafes?", optionA: "Food stalls", optionB: "City cafes" },
  { question: "Do you like group projects?", optionA: "Yes", optionB: "Hate them" },
  { question: "Snapchat or Instagram?", optionA: "Snapchat", optionB: "Instagram" },
  { question: "Linux or Windows?", optionA: "Linux", optionB: "Windows" },
  { question: "VIT tech events: Fun or boring?", optionA: "Fun!", optionB: "Boring" },
  { question: "Would you date a batchmate?", optionA: "Yes", optionB: "No" },
  { question: "Part-time job or chill?", optionA: "Job", optionB: "Chill" },
  { question: "CGPA or startup dream?", optionA: "CGPA", optionB: "Startup" },
  { question: "Laptop stickers: Cool or cringe?", optionA: "Cool", optionB: "Cringe" },
  { question: "Would you marry a VITian?", optionA: "Yes", optionB: "Let’s see" },
  { question: "Did you ever fake sick to skip class?", optionA: "Many times", optionB: "Never" },
  { question: "Python or Java?", optionA: "Python", optionB: "Java" },
  { question: "LinkedIn addict or Instagram model?", optionA: "LinkedIn", optionB: "Instagram" },
  { question: "Rewatch F.R.I.E.N.D.S or try new?", optionA: "Rewatch", optionB: "Try new" },
  { question: "Gym or Sleep?", optionA: "Gym", optionB: "Sleep" },
  { question: "Plan assignments or wing it?", optionA: "Plan", optionB: "Wing it" },
  { question: "Night canteen or 7 PM dinner?", optionA: "Night canteen", optionB: "7 PM dinner" },
  { question: "Chai breaks every day?", optionA: "Yes", optionB: "Nope" },
  { question: "VIT OP hostel or main hostel?", optionA: "OP", optionB: "Main" },
  { question: "Hackathons or fests?", optionA: "Hackathons", optionB: "Fests" },
  { question: "F.R.I.E.N.D.S or Big Bang Theory?", optionA: "F.R.I.E.N.D.S", optionB: "BBT" },
  { question: "Crush in class?", optionA: "Yes", optionB: "No" },
  { question: "Android or iOS?", optionA: "Android", optionB: "iOS" },
  { question: "Spoken to a VIT senior?", optionA: "Yeah", optionB: "Not yet" },
  { question: "Should attendance be optional?", optionA: "YES!", optionB: "No, it’s okay" },
  { question: "Are clubs actually useful?", optionA: "Very", optionB: "Nope" },
  { question: "Do you prefer hybrid classes?", optionA: "Yes", optionB: "No" },
  { question: "Online exams or offline?", optionA: "Online", optionB: "Offline" },
  { question: "Daily bathing in hostel?", optionA: "Everyday", optionB: "Sometimes" },
  { question: "Game night or movie night?", optionA: "Game night", optionB: "Movie night" },
  { question: "Do you know VIT dress code?", optionA: "Yes", optionB: "Wait…what?" },
  { question: "Internship in Chennai or abroad?", optionA: "Chennai", optionB: "Abroad" },
  { question: "Does GPA matter?", optionA: "A lot", optionB: "Not really" },
  { question: "VIT VTOP UI: Decent or disaster?", optionA: "Decent", optionB: "Disaster" },
  { question: "Online crush in class group?", optionA: "Guilty", optionB: "Nope" },
  { question: "Would you work on campus?", optionA: "Yes", optionB: "No" },
  { question: "Do you remember your VITEE rank?", optionA: "Yes", optionB: "I buried it" },
  { question: "First crush was from VIT?", optionA: "Yes", optionB: "No" },
  { question: "Sneaked out of hostel?", optionA: "Yes", optionB: "Never" },
  { question: "Ever argued with faculty?", optionA: "Yes", optionB: "No" },
  { question: "VIT - strict or chill?", optionA: "Strict", optionB: "Chill" },
  { question: "Do you miss school days?", optionA: "Yes", optionB: "Not really" },
  { question: "Do you think you’ll pass all subjects?", optionA: "Of course", optionB: "Let’s hope" },
  { question: "Do you believe in love at VIT?", optionA: "Yes", optionB: "LMAO no" }
];


Question.insertMany(questions)
  .then(() => {
    console.log('Questions seeded!');
    mongoose.disconnect();
  })
  .catch(err => {
    console.error(err);
    mongoose.disconnect();
  }); 
